### ISSUE TITLE
dokku edgedb:upgrade nightly fails

### ISSUE THREAD

**Issue by Jarrodsz** [IgnisDa/dokku-edgedb#8] opened 2023-03-15 11:13 UTC
```root@ubuntu-s-1vcpu-2gb-amd-fra1-01:~# dokku edgedb:upgrade nightly
 !     Edgedb service nightly does not exist
root@ubuntu-s-1vcpu-2gb-amd-fra1-01:~# dokku edgedb:upgrade training nightly
=====> Upgrading training to edgedb/edgedb:2.11
=====> Stopping training
=====> Pausing container
       Container paused
       Removing container
=====> Starting container
       Waiting for container to be ready
       Linking edgedb instance
[2023-03-15T11:11:52Z WARN  edgedb::version_check] Newer version of edgedb tool exists 2.3.1+ef99779 (current 2.2.6+b869667)
Trusting unknown server certificate: SHA1:___XXX___
/.config/edgedb/credentials/training.json exists! Overwrite? (type `Yes`)
edgedb error: EOF```

**Comment by IgnisDa** [comment] 2023-03-16 00:38
I can reproduce it. The problem is that the command does not seem to be non-interactive, so there is no easy way to accept the prompt. I will ask in the Edgedb Discord if it is possible to do it via an environment variable.

**Comment by IgnisDa** [comment] 2023-03-16 01:14
@Jarrodsz I pushed a fix. Could you update the plugin and try again?

**Closed as completed** 2023-03-16 13:09 UTC
